### PR TITLE
GeoDataFrame structure figure

### PR DESCRIPTION
**Pull request by michaeldorman**

### CODE REVIEW

**Review by Robinlovelace — APPROVED** [review]

**Review by anitagraser — COMMENTED** [review]
The gdf structure image is great. It nicely illustrates the concepts and terminology. The gdf flow figure does not provide much extra information as far as I can see

**Comment by michaeldorman** [comment]
> The gdf structure image is great. It nicely illustrates the concepts and terminology. The gdf flow figure does not provide much extra information as far as I can see

Thanks @anitagraser ! The flow figure adds the roadmap of the operations to create a layer from scratch (such as how and when the `gpd.Series` and `gpd.DataFrame` functions are used). Maybe we can combine the two figures into one? That is, at the "end" of the flow figure, we show the `GeoDataFrame` with components marked (which is now in a separate figure). Will be happy to hear what you think.

**Comment by Nowosad** [comment]
Hi @michaeldorman -- it is a nice figure. I would just suggest to modify the colors (I suspect that they are not good for people with color deficiencies).

**Comment by michaeldorman** [comment]
> Hi @michaeldorman -- it is a nice figure. I would just suggest to modify the colors (I suspect that they are not good for people with color deficiencies).

Thanks @Nowosad , good idea! Please see https://github.com/geocompx/py/pull/141/commits/d00d1e85218e80398e875acfc8c5fbc7954532c0 (this palette is defined "color blind friendly")

**Comment by anitagraser** [comment]
Ah, I see. I must have missed some details on the phone preview

**Comment by Nowosad** [comment]
@michaeldorman looks great now.

**Comment by michaeldorman** [comment]
> @michaeldorman looks great now.

Thanks @Nowosad

**Pull request merged**
